---

- name: "Set CA certificate and key file path names"
  set_fact:
    tls_cacert_path: "/tmp/tls.crt"
    tls_cakey_path: "/tmp/tls.key"

- name: "Create the CA certificate and key"
  command: >
    openssl req -newkey rsa:2048 -new -x509 -days 365 -nodes
    -out {{ tls_cacert_path }} -keyout {{ tls_cakey_path }} -subj "{{ tls_casubjectDistinguishedName }}"

# Work-around k8s_raw inability to create Secret directly
- name: "ca secret state={{ state }}"
  block:
    - name: "Create ca secret from template"
      template:
        src: ca_secret.yml.j2
        dest: /tmp/ca_secret.yml

    - name: "Create ca secret"
      shell: kubectl create --filename=/tmp/ca_secret.yml
  when: state == "present"
