---

- name: "set fact statefulset persistentvolumeclaims"
  block:
  - name: "Register statefulset json cmd"
    shell: kubectl get sts {{ name }} -o json
    register: sts_cmd

  - name: "Set Fact statefulset json"
    set_fact:
      sts_json: "{{ sts_cmd.stdout | from_json }}"

  - name: "Set Fact statefulset replicas sequence"
    set_fact:
      sts_status_replicas_list: "{{ sts_status_replicas_list }} + [ '{{ item }}' ]"
    with_sequence: "{{ 'start=0 end=' + (((sts_status_replicas | int) - 1) | string) }}"

  - name: "Set Fact statefulset persistentvolumeclaims"
    set_fact:
      statefulset_pvcs: "{{ statefulset_pvcs }} + [ '{{ item.0 + '-' + name + '-' + item.1 }}' ]"
    with_nested:
      - "{{ sts_spec_volume_claim_templates }}"
      - "{{ sts_status_replicas_list }}"

  vars:
    sts_status_replicas_list: []
    sts_status_replicas: "{{ sts_json | json_query('status.replicas') | int }}"
    sts_spec_volume_claim_templates: "{{ sts_json | json_query('spec.volumeClaimTemplates[*].metadata.name') }}"
