apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "fullname" . }}
    component: sginit
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    sgadmincert: "true"
  name: {{ template "fullname" . }}-admin-cert-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
