apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-kibana-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  kibana.yml: |-

    xpack.security.enabled: false
    xpack.ml.enabled: false
    xpack.graph.enabled: false


    server.name: kibana
    server.host: "0"

    #elasticsearch.url: VIAENV

    elasticsearch.username: "kibanaserver"
    #elasticsearch.password: VIAENV

    # SSL for outgoing requests from the Kibana Server to the browser (PEM formatted)
    server.ssl.enabled: true
    #server.ssl.certificate: VIAENV
    #server.ssl.key: VIAENV

    # If you need to provide a CA certificate for your Elasticsearch instance, put
    # the path of the pem file here.
    elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/certificates-secrets/root-ca.pem"]

    # Set to false to have a complete disregard for the validity of the SSL
    # certificate.
    #elasticsearch.ssl.verificationMode: certificate

    # If you would like to send the log output to a file you can set the path below.
    logging.dest: stdout

    # Set this to true to suppress all logging output except for error messages.
    logging.quiet: false
    logging.verbose: false
    
    #### Search Guard specific config ####
    searchguard.multitenancy.enabled: true

    # Allow cookies only via HTTPS. Cookies transmitted via HTTP will be discarded silently, i.e. a login is not possible.
    searchguard.cookie.secure: true
    # Password used to encrypt the session cookie. Must be at least 32 characters.
    #searchguard.cookie.password: VIAENV

    #### Additional config ####
{{- if .Values.kibana.config }}
{{ toYaml .Values.kibana.config | indent 4 }}
{{- end }}
